apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: IMAGE
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          envFrom:
          - configMapRef:
              name: app-config
          ports:
          - containerPort: 8080
            name: theport
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
      restartPolicy: Always
