apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot

images:
- name: IMAGE
  newName: quay.io/jkeam/simple-chatbot
  digest: sha256:247f0dc7e8997755c8c1f1d72ba7ac870dc84e06511479809c1f93a735cf0e27

configMapGenerator:
- name: app-config
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml
- route.yaml
- console-link.yaml
