apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot

images:
- name: IMAGE
  newName: quay.io/jkeam/simple-chatbot
  digest: sha256:e624324140592835cdec605d871ad157c0436a4f363311016e657dfc30c4e67e

configMapGenerator:
- name: app-config
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml
- route.yaml
- console-link.yaml
