apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot

images:
- name: IMAGE
  newName: quay.io/jkeam/simple-chatbot
  digest: sha256:563cc0a1b27d650c3c2e0dd2ecc540c5500c31f629088a6a95cf22bf7ffdb111

configMapGenerator:
- name: app-config
  envs:
  - .env

resources:
- deployment.yaml
- service.yaml
- route.yaml
- console-link.yaml
